[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "cascade"
version = "0.56.0"
description = "Command-Line Audio Stream Capture And Decoding Engine"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
authors = [{name="Edward", email="muzhi1014@outlook.com"}]
keywords = [
    "music-player",
    "audio-player",
    "command-line",
    "cli",
    "tui",
    "terminal",
    "playlist",
    "lyrics",
    ]
classifiers = ["Programming Language :: Python :: 3"]
requires-python = ">=3.12"
dependencies = [
    "platformdirs>=4.0",
    "python-vlc>=3.0",
    "readchar>=4.0",
    "mutagen>=1.48",
    "pynput>=1.8",
    "wcwidth>=0.2",
    "psutil>=7.0",
    "tomli-w>=1.0",
    "pystray>=0.19",
    "pillow>=12.0",
    "syncedlyrics>=1.0",
    "just_playback>=0.1.9",
]

[project.urls]
Repository = "https://github.com/askformeal/CASCADE"

[project.scripts]
cascade = "src.frontend.cli.core:main"

[tool.setuptools.packages.find]
include = ["src*", "res*"]

[tool.setuptools.package-data]
res = ["*.ico", "*.png", "*.txt", "*/*.png"]

[tool.bumpversion]
current_version = "0.56.0"
[[tool.bumpversion.files]]
filename = "src/__init__.py"
search = "__version__ = '{current_version}'"
replace = "__version__ = '{new_version}'"